# Generated by Django 4.2.2 on 2025-09-21 11:57

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_Primium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('profileimage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_secondary', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_no', models.CharField(blank=True, max_length=100, null=True)),
                ('companyname', models.CharField(blank=True, max_length=100, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('companylogo', models.ImageField(blank=True, default='https://png.pngtree.com/thumb_back/fh260/background/20200714/pngtree-modern-double-color-futuristic-neon-background-image_351866.jpg', null=True, upload_to='images/')),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('company_website', models.CharField(blank=True, default='https://websenz.in/', max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('location_url', models.URLField(blank=True, null=True)),
                ('nature_of_business', models.CharField(blank=True, max_length=200, null=True)),
                ('start_year', models.DateField(blank=True, default=datetime.date(2000, 1, 1), help_text='Enter the date the company was started.', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1800, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2025, 9, 21))])),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('pinterest_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('telegram_url', models.URLField(blank=True, null=True)),
                ('speciality_1', models.CharField(blank=True, max_length=200, null=True)),
                ('speciality_2', models.CharField(blank=True, max_length=200, null=True)),
                ('speciality_3', models.CharField(blank=True, max_length=200, null=True)),
                ('gallery_imagePrimium1', models.ImageField(blank=True, null=True, upload_to='premium_gallery/')),
                ('gallery_imagePrimium2', models.ImageField(blank=True, null=True, upload_to='premium_gallery/')),
                ('gallery_imagePrimium3', models.ImageField(blank=True, null=True, upload_to='premium_gallery/')),
                ('gallery_imagePrimium4', models.ImageField(blank=True, null=True, upload_to='premium_gallery/')),
                ('gallery_imagePrimium5', models.ImageField(blank=True, null=True, upload_to='premium_gallery/')),
                ('gallery_imagePrimium6', models.ImageField(blank=True, null=True, upload_to='premium_gallery/')),
                ('gallery_imagePrimium7', models.ImageField(blank=True, null=True, upload_to='premium_gallery/')),
                ('last_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('profileimage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('companyname', models.CharField(blank=True, max_length=100, null=True)),
                ('companylogo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('company_website', models.CharField(blank=True, default='https://anitatai.in/', max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('gallery_image1', models.ImageField(blank=True, null=True, upload_to='basic_gallery/')),
                ('gallery_image2', models.ImageField(blank=True, null=True, upload_to='basic_gallery/')),
                ('gallery_image3', models.ImageField(blank=True, null=True, upload_to='basic_gallery/')),
                ('gallery_image4', models.ImageField(blank=True, null=True, upload_to='basic_gallery/')),
                ('gallery_image5', models.ImageField(blank=True, null=True, upload_to='basic_gallery/')),
                ('gallery_image6', models.ImageField(blank=True, null=True, upload_to='basic_gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
