# Generated by Django 4.2.2 on 2024-09-27 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Detail_Primium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(max_length=100)),
                ("profileimage", models.ImageField(upload_to="images/")),
                ("phone", models.CharField(max_length=100)),
                (
                    "phone_secondary",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "whatsapp_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("companyname", models.CharField(max_length=100)),
                (
                    "company_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "companylogo",
                    models.ImageField(
                        default="https://png.pngtree.com/thumb_back/fh260/background/20200714/pngtree-modern-double-color-futuristic-neon-background-image_351866.jpg",
                        upload_to="images/",
                    ),
                ),
                ("website", models.CharField(max_length=500)),
                (
                    "company_website",
                    models.CharField(default="https://websenz.in/", max_length=100),
                ),
                ("address", models.CharField(max_length=500)),
                ("location_url", models.URLField(blank=True, null=True)),
                (
                    "nature_of_business",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("facebook_url", models.URLField(blank=True, null=True)),
                ("twitter_url", models.URLField(blank=True, null=True)),
                ("instagram_url", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                ("pinterest_url", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("telegram_url", models.URLField(blank=True, null=True)),
                (
                    "speciality_1",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "speciality_2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "speciality_3",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "gallery_imagePrimium1",
                    models.ImageField(blank=True, null=True, upload_to="gallery/"),
                ),
                (
                    "gallery_imagePrimium2",
                    models.ImageField(blank=True, null=True, upload_to="gallery/"),
                ),
                (
                    "gallery_imagePrimium3",
                    models.ImageField(blank=True, null=True, upload_to="gallery/"),
                ),
                (
                    "gallery_imagePrimium4",
                    models.ImageField(blank=True, null=True, upload_to="gallery/"),
                ),
                (
                    "gallery_imagePrimium5",
                    models.ImageField(blank=True, null=True, upload_to="gallery/"),
                ),
                (
                    "gallery_imagePrimium6",
                    models.ImageField(blank=True, null=True, upload_to="gallery/"),
                ),
                (
                    "gallery_imagePrimium7",
                    models.ImageField(
                        blank=True,
                        default="https://png.pngtree.com/thumb_back/fh260/background/20200714/pngtree-modern-double-color-futuristic-neon-background-image_351866.jpg",
                        null=True,
                        upload_to="gallery/",
                    ),
                ),
                ("last_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(max_length=100)),
                ("profileimage", models.ImageField(upload_to="images/")),
                ("phone", models.CharField(max_length=100)),
                ("companyname", models.CharField(max_length=100)),
                ("companylogo", models.ImageField(upload_to="images/")),
                ("website", models.CharField(max_length=500)),
                (
                    "company_website",
                    models.CharField(default="https://websenz.in/", max_length=100),
                ),
                ("address", models.CharField(max_length=500)),
                (
                    "gallery_image1",
                    models.ImageField(blank=True, null=True, upload_to="gallery/"),
                ),
                (
                    "gallery_image2",
                    models.ImageField(blank=True, null=True, upload_to="gallery/"),
                ),
                (
                    "gallery_image3",
                    models.ImageField(blank=True, null=True, upload_to="gallery/"),
                ),
                (
                    "gallery_image4",
                    models.ImageField(blank=True, null=True, upload_to="gallery/"),
                ),
                (
                    "gallery_image5",
                    models.ImageField(blank=True, null=True, upload_to="gallery/"),
                ),
                (
                    "gallery_image6",
                    models.ImageField(blank=True, null=True, upload_to="gallery/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_for",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
