# Generated by Django 4.2.2 on 2024-09-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail_primium",
            name="gallery_imagePrimium7",
            field=models.ImageField(blank=True, null=True, upload_to="gallery/"),
        ),
    ]
