# Generated by Django 4.2.2 on 2024-09-28 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0002_alter_detail_primium_gallery_imageprimium7"),
    ]

    operations = [
        migrations.AddField(
            model_name="detail_primium",
            name="start_year",
            field=models.IntegerField(
                default=2000,
                help_text="Enter the year the company was started.",
                validators=[
                    django.core.validators.MinValueValidator(1800),
                    django.core.validators.MaxValueValidator(2024),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="detail",
            name="gallery_image1",
            field=models.ImageField(blank=True, null=True, upload_to="basic_gallery/"),
        ),
        migrations.AlterField(
            model_name="detail",
            name="gallery_image2",
            field=models.ImageField(blank=True, null=True, upload_to="basic_gallery/"),
        ),
        migrations.AlterField(
            model_name="detail",
            name="gallery_image3",
            field=models.ImageField(blank=True, null=True, upload_to="basic_gallery/"),
        ),
        migrations.AlterField(
            model_name="detail",
            name="gallery_image4",
            field=models.ImageField(blank=True, null=True, upload_to="basic_gallery/"),
        ),
        migrations.AlterField(
            model_name="detail",
            name="gallery_image5",
            field=models.ImageField(blank=True, null=True, upload_to="basic_gallery/"),
        ),
        migrations.AlterField(
            model_name="detail",
            name="gallery_image6",
            field=models.ImageField(blank=True, null=True, upload_to="basic_gallery/"),
        ),
        migrations.AlterField(
            model_name="detail_primium",
            name="gallery_imagePrimium1",
            field=models.ImageField(
                blank=True, null=True, upload_to="premium_gallery/"
            ),
        ),
        migrations.AlterField(
            model_name="detail_primium",
            name="gallery_imagePrimium2",
            field=models.ImageField(
                blank=True, null=True, upload_to="premium_gallery/"
            ),
        ),
        migrations.AlterField(
            model_name="detail_primium",
            name="gallery_imagePrimium3",
            field=models.ImageField(
                blank=True, null=True, upload_to="premium_gallery/"
            ),
        ),
        migrations.AlterField(
            model_name="detail_primium",
            name="gallery_imagePrimium4",
            field=models.ImageField(
                blank=True, null=True, upload_to="premium_gallery/"
            ),
        ),
        migrations.AlterField(
            model_name="detail_primium",
            name="gallery_imagePrimium5",
            field=models.ImageField(
                blank=True, null=True, upload_to="premium_gallery/"
            ),
        ),
        migrations.AlterField(
            model_name="detail_primium",
            name="gallery_imagePrimium6",
            field=models.ImageField(
                blank=True, null=True, upload_to="premium_gallery/"
            ),
        ),
        migrations.AlterField(
            model_name="detail_primium",
            name="gallery_imagePrimium7",
            field=models.ImageField(
                blank=True, null=True, upload_to="premium_gallery/"
            ),
        ),
    ]
