# Generated by Django 4.2.2 on 2025-09-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_detail_primium_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_primium',
            name='company_website',
            field=models.CharField(blank=True, default='none', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail_primium',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail_primium',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail_primium',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail_primium',
            name='location_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail_primium',
            name='pinterest_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail_primium',
            name='telegram_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail_primium',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail_primium',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
