# Generated by Django 4.2.2 on 2024-09-28 09:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cards", "0003_detail_primium_start_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detail_primium",
            name="start_year",
            field=models.DateField(
                default=datetime.date(2000, 1, 1),
                help_text="Enter the date the company was started.",
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(1800, 1, 1)),
                    django.core.validators.MaxValueValidator(
                        datetime.date(2024, 9, 28)
                    ),
                ],
            ),
        ),
    ]
