# Generated by Django 4.2.2 on 2025-09-21 20:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_detail_primium_company_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_primium',
            name='companylogo',
            field=models.ImageField(blank=True, default='none', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='detail_primium',
            name='speciality_1',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=200, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='detail_primium',
            name='speciality_2',
            field=models.CharField(blank=True, choices=[('below_18', '<18'), ('18_40', '18-40'), ('above_40', '>40')], max_length=200, null=True, verbose_name='Age Group'),
        ),
        migrations.AlterField(
            model_name='detail_primium',
            name='start_year',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1), help_text='Enter the date the company was started.', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1800, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2025, 9, 22))]),
        ),
    ]
