# Generated by Django 4.2.2 on 2025-09-21 05:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_detail_address_alter_detail_company_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_primium',
            name='start_year',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1), help_text='Enter the date the company was started.', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1800, 1, 1)), django.core.validators.MaxValueValidator(datetime.date(2025, 9, 21))]),
        ),
    ]
